window.RRFC_LEAGUES = [
  {
    id: "rrfc",
    name: "RRFC",
    fullName: "Rec Room Football Community",
    active: true,
    note: "Current league",
  },
  {
    id: "rrfo",
    name: "RRFO",
    fullName: "Older Rec Room football league",
    active: false,
    note: "No longer active — predecessor league",
  },
  {
    id: "rrfa",
    name: "RRFA",
    fullName: "Older Rec Room football league",
    active: false,
    note: "No longer active — predecessor league",
  },
];

window.RRFC_CHAMPIONSHIPS = {
  rrfc: [
    {
      season: 1,
      champion: "Notre Dame Fighting Irish",
      opponent: "Louisville Cardinals",
      mvp: "Jondoge13",
    },
    {
      season: 2,
      champion: "Texas Tech Red Raiders",
      opponent: "Coastal Carolina Chanticleers",
      mvp: "Contate",
    },
    {
      season: 3,
      champion: "Auburn Tigers",
      opponent: "Colorado Buffaloes",
      mvp: "KingEnvy",
    },
    {
      season: 4,
      champion: "Oklahoma Sooner",
      opponent: "Miami Hurricanes",
      mvp: "Kazu",
    },
    {
      season: 5,
      champion: "Northern Illinois Huskies",
      opponent: "Penn State Nittany Lions",
      mvp: "Nate Jr.",
    },
    {
      season: 6,
      champion: "Rutgers Scarlett Knights",
      opponent: "South Alabama Jaguars",
      mvp: "Miri",
    },
    {
      season: 7,
      champion: "New York Jets",
      opponent: "Washington Commanders",
      mvp: "OBJColorz",
    },
    {
      season: 8,
      champion: "Dallas Cowboys",
      opponent: "New Orleans Saints",
      mvp: "DeeMontana",
    },
    {
      season: 9,
      champion: "Baltimore Huskies",
      opponent: "Star Regiment",
      mvp: "Mike",
    },
    {
      season: 10,
      champion: "Las Vegas Leviathans",
      opponent: "Baltimore Huskies",
      mvp: "Luigi",
    },
  ],
  rrfo: [
    {
      season: 1,
      champion: "Duke Blue Devils",
      opponent: "Florida Bucks",
      mvp: "BabyJustin",
    },
    {
      season: 2,
      champion: "Suwannee Firebirds",
      opponent: "Kolkata Vipers",
      mvp: "Chamele",
    },
    {
      season: 3,
      champion: "Atlanta Legends",
      opponent: "Jaguars",
      mvp: "Vex",
    },
    {
      season: 4,
      champion: "Duke Red Devils",
      opponent: "Congo Ben Simmons",
      mvp: "Mike",
    },
    {
      season: 5,
      champion: "Philadelphia Eagles",
      opponent: "New England Patriots",
      mvp: "Bossness",
    },
    {
      season: 6,
      champion: "Kansas City Chiefs",
      opponent: "Los Angeles Rams",
      mvp: "Batman",
    },
    {
      season: 7,
      champion: "LSU Tigers",
      opponent: "Washington Huskies",
      mvp: "Kraak",
    },
    {
      season: 8,
      champion: "New England Elite",
      opponent: "New York Rollers",
      mvp: "ZK",
    },
    {
      season: 9,
      champion: "Baltimore Ravens",
      opponent: "Philadelphia Eagles",
      mvp: "Batman",
    },
    {
      season: 10,
      champion: "Rahway Revenge",
      opponent: "Seattle Evergreen",
      mvp: "Chee",
    },
    {
      season: 11,
      champion: "Oregon State Beavers",
      opponent: "Penn State Nittany Lions",
      mvp: "Jordan",
    },
  ],
  rrfa: [
    {
      season: 1,
      champion: "Kansas Jayhawks",
      opponent: "Army Black Nights",
      mvp: "Kamargielaa",
    },
    {
      season: 2,
      champion: "Sharpshooters",
      opponent: "Nike",
      mvp: "Pillow",
    },
    {
      season: 3,
      champion: "Las Vegas Vengeance",
      opponent: "Florida Bucks",
      mvp: "BF",
    },
    {
      season: 4,
      champion: "Las Vegas Vengeance",
      opponent: "Chicago Ghost",
      mvp: "Nate Jr.",
    },
    {
      season: 5,
      champion: "Baltimore Beagles",
      opponent: "Duke Red Devils",
      mvp: "Pillow",
    },
    {
      season: 6,
      champion: "Baltimore Juniors",
      opponent: "Baltimore Huskies",
      mvp: "Keanu",
    },
  ],
};

window.RRFC_AWARD_LABELS = {
  MVP: "Most Valuable Player",
  ROTY: "Rookie of the Year",
  MIP: "Most Improved Player",
  COTY: "Coach of the Year",
  Sleeper: "Sleeper",
  DBOTY: "Defensive Back of the Year",
  WROTY: "Wide Receiver of the Year",
  QBOTY: "Quarterback of the Year",
  RBOTY: "Running Back of the Year",
};

window.RRFC_AWARD_ORDER = [
  "MVP",
  "QBOTY",
  "WROTY",
  "RBOTY",
  "DBOTY",
  "ROTY",
  "MIP",
  "Sleeper",
  "COTY",
];

window.RRFC_SEASON_AWARDS = [
  {
    season: 1,
    awards: {
      MVP: "Vex",
      ROTY: "Yank",
      MIP: "Kayden",
      COTY: "Chee",
      Sleeper: "Dylan",
      DBOTY: "Miri",
      WROTY: "Batman",
      QBOTY: "Jordan",
      RBOTY: "BF",
    },
  },
  {
    season: 2,
    awards: {
      MVP: "Yin",
      ROTY: "Junk",
      MIP: "OBJ",
      COTY: "Jevsal",
      Sleeper: "Genz",
      DBOTY: "Profit",
      WROTY: "Yin",
      QBOTY: "Solar",
    },
  },
  {
    season: 3,
    awards: {
      MVP: "Unc Mike",
      MIP: "Wo",
      COTY: "Ben",
      Sleeper: "Mood",
      DBOTY: "Miri",
      WROTY: "Contate",
      RBOTY: "Yang",
      QBOTY: "Dax",
    },
  },
  {
    season: 4,
    awards: {
      MVP: "Miri",
      MIP: "Kratos",
      COTY: "Mood",
      Sleeper: "Ryder",
      DBOTY: "Miri",
      WROTY: "Miri",
      RBOTY: "BF",
      QBOTY: "Unc Mike",
    },
  },
  {
    season: 5,
    awards: {
      MVP: "Kamar",
      QBOTY: "Kamar",
      WROTY: "Ben",
      DBOTY: "Kazu",
      RBOTY: "Nate",
      MIP: "Ryder",
      COTY: "Nate",
      ROTY: "Xpgzz",
    },
  },
  {
    season: 6,
    awards: {
      MVP: "Kazu",
      QBOTY: "Chee",
      WROTY: "Elite",
      DBOTY: "Pabyo",
      RBOTY: "BF",
      MIP: "Mario",
      Sleeper: "Mario",
      COTY: "Chee",
    },
  },
  {
    season: 7,
    awards: {
      MVP: "Kazu",
      QBOTY: "Unc Mike",
      WROTY: "Elite",
      DBOTY: "Miri",
      RBOTY: "Mood",
      MIP: "SlashPass",
      Sleeper: "Xpgzz",
      COTY: "Kazu",
    },
  },
  {
    season: 8,
    awards: {
      MVP: "Jordan",
      QBOTY: "Chee",
      WROTY: "Miri",
      RBOTY: "Bossness",
      DBOTY: "ZK",
      ROTY: "Ink",
      MIP: "Beep",
      Sleeper: "Mikey",
      COTY: "Ben",
    },
  },
];
