/* RRFC players
 *
 * When updating an overall later, set prevOvr to the old number:
 *   { name: "Miri", ovr: 97, prevOvr: 96, club: "90" }
 * Leave prevOvr out (or equal to ovr) if it hasn't changed — it won't show.
 */
window.RRFC_PLAYERS = [
  // 90's Club
  { name: "Miri", ovr: 96, club: "90" },
  { name: "Kazu", ovr: 96, club: "90" },
  { name: "Yin", ovr: 95, club: "90" },
  { name: "Vex", ovr: 95, club: "90" },
  { name: "Mario", ovr: 94, club: "90" },
  { name: "Purp", ovr: 94, club: "90" },
  { name: "Chee", ovr: 93, club: "90" },
  { name: "Batman", ovr: 92, club: "90" },
  { name: "Kayden", ovr: 92, club: "90" },
  { name: "Revanue", ovr: 92, club: "90" },
  { name: "Kratos", ovr: 91, club: "90" },
  { name: "Error", ovr: 91, club: "90" },
  { name: "Selfmadejay", ovr: 90, club: "90" },
  { name: "Wo", ovr: 90, club: "90" },
  { name: "SlashPass", ovr: 90, club: "90" },
  { name: "Shark", ovr: 90, club: "90" },

  // 80's Club
  { name: "XPGzz", ovr: 89, club: "80" },
  { name: "Dylan", ovr: 89, club: "80" },
  { name: "Bilxa", ovr: 88, club: "80" },
  { name: "Yang", ovr: 88, club: "80" },
  { name: "Bearvr", ovr: 88, club: "80" },
  { name: "Bensimmons", ovr: 88, club: "80" },
  { name: "Nao", ovr: 87, club: "80" },
  { name: "Mood", ovr: 87, club: "80" },
  { name: "Minivip", ovr: 86, club: "80" },
  { name: "Kiwiz", ovr: 86, club: "80" },
  { name: "Venus", ovr: 86, club: "80" },
  { name: "BEEEP", ovr: 86, club: "80" },
  {
    name: "ZK",
    ovr: 86,
    club: "80",
    note: "Would be way higher but headset broke",
  },
  { name: "Kaizen", ovr: 85, club: "80" },
  { name: "Apx11o", ovr: 85, club: "80", aliases: ["Apollo"] },
  { name: "icy", ovr: 84, club: "80" },
  { name: "Bossness", ovr: 84, club: "80" },
  { name: "Noah", ovr: 83, club: "80" },
  { name: "Sbflow", ovr: 83, club: "80" },
  { name: "Kye", ovr: 82, club: "80" },
  { name: "MiniJR", ovr: 82, club: "80" },
  { name: "Genz", ovr: 81, club: "80" },
  { name: "Zir", ovr: 81, club: "80" },
  { name: "Gorilla", ovr: 80, club: "80" },
  { name: "Mike", ovr: 80, club: "80" },
  { name: "SlimJim", ovr: 80, club: "80" },

  // 70's Club
  { name: "Luigi?", ovr: 79, club: "70" },
  { name: "Spaz", ovr: 79, club: "70" },
  { name: "Tyrone", ovr: 79, club: "70" },
  { name: "Javo", ovr: 79, club: "70" },
  { name: "Pabyo", ovr: 79, club: "70" },
  { name: "Rain", ovr: 79, club: "70" },
  { name: "Trey/Flock", ovr: 79, club: "70" },
  { name: "Kakarat", ovr: 78, club: "70" },
  { name: "AppleAJ", ovr: 78, club: "70", aliases: ["Aj", "AJ"] },
  { name: "Mar", ovr: 78, club: "70" },
  { name: "5starmax", ovr: 78, club: "70", aliases: ["Max"] },
  { name: "Deer", ovr: 78, club: "70" },
  { name: "Mikey", ovr: 78, club: "70" },
  { name: "Straw", ovr: 78, club: "70" },
  { name: "Nadia", ovr: 77, club: "70" },
  { name: "Joker", ovr: 77, club: "70" },
  { name: "Dez", ovr: 77, club: "70" },
  { name: "BabyTray", ovr: 77, club: "70" },
  { name: "PAP2Mangee", ovr: 76, club: "70" },
  { name: "KJ", ovr: 76, club: "70" },
  { name: "Davieon", ovr: 76, club: "70" },
  { name: "CYBER", ovr: 76, club: "70" },
  { name: "Zay", ovr: 75, club: "70" },
  { name: "Ballhawk", ovr: 75, club: "70" },
  { name: "Yilo", ovr: 74, club: "70" },
  { name: "Polo", ovr: 74, club: "70" },
  { name: "Mars", ovr: 74, club: "70" },
  { name: "D2 Crazy", ovr: 74, club: "70", aliases: ["Crazy"] },
  { name: "Sasuke", ovr: 73, club: "70" },
  { name: "ASPshimmy", ovr: 73, club: "70" },
  { name: "Spoon", ovr: 73, club: "70" },
  { name: "Zermis", ovr: 73, club: "70" },
  { name: "VIPBaby", ovr: 72, club: "70" },
  { name: "Tyler", ovr: 72, club: "70" },
  { name: "TDLMarcus", ovr: 72, club: "70" },
  { name: "Smokey", ovr: 72, club: "70" },
  { name: "Elijah", ovr: 72, club: "70" },
  { name: "JT", ovr: 71, club: "70" },
  { name: "MVP", ovr: 71, club: "70" },
  { name: "MalMal", ovr: 71, club: "70" },
  { name: "f4zyw0rld.", ovr: 70, club: "70" },
  { name: "nico", ovr: 70, club: "70" },
  { name: "KingDrip", ovr: 70, club: "70" },
  { name: "Sojay", ovr: 70, club: "70" },
  { name: "Fhonts", ovr: 70, club: "70" },
  { name: "Mait", ovr: 70, club: "70" },
  { name: "pittman", ovr: 70, club: "70" },
];

window.RRFC_CLUBS = [
  { id: "90", label: "90's Club", range: "90–96 OVR" },
  { id: "80", label: "80's Club", range: "80–89 OVR" },
  { id: "70", label: "70's Club", range: "70–79 OVR" },
];
