window.RRFC_SCHEDULE = [
  {
    id: "week-1",
    title: "Week 1",
    auto: "7/14",
    games: [
      { time: "7:00 PM", home: "Ball State Cardinals", away: "Michigan Wolverines" },
      { time: "7:30 PM", home: "Oregon State Beavers", away: "Cincinnati Bearcats" },
      { time: "8:30 PM", home: "Texas Longhorns", away: "Florida Gators" },
      { time: "9:30 PM", home: "Liberty Flames", away: "Missouri Tigers" },
      { time: "10:00 PM", home: "Oregon Ducks", away: "Hawaii Rainbow Warriors" },
    ],
  },
  {
    id: "week-2",
    title: "Week 2",
    auto: "7/18",
    games: [
      { time: "7:00 PM", home: "Oregon Ducks", away: "Michigan Wolverines" },
      { time: "7:30 PM", home: "Texas Longhorns", away: "Cincinnati Bearcats" },
      { time: "8:30 PM", home: "Liberty Flames", away: "Ball State Cardinals" },
      { time: "9:30 PM", home: "Florida Gators", away: "Hawaii Rainbow Warriors" },
      { time: "10:00 PM", home: "Oregon State Beavers", away: "Missouri Tigers" },
    ],
  },
  {
    id: "week-3",
    title: "Week 3",
    auto: "7/22",
    games: [
      { time: "7:00 PM", home: "Florida Gators", away: "Michigan Wolverines" },
      { time: "7:30 PM", home: "Oregon Ducks", away: "Liberty Flames" },
      { time: "8:30 PM", home: "Cincinnati Bearcats", away: "Missouri Tigers" },
      { time: "9:30 PM", home: "Oregon State Beavers", away: "Ball State Cardinals" },
      { time: "10:00 PM", home: "Texas Longhorns", away: "Hawaii Rainbow Warriors" },
    ],
  },
  {
    id: "week-4",
    title: "Week 4",
    auto: "7/26",
    games: [
      { time: "7:00 PM", home: "Oregon State Beavers", away: "Oregon Ducks" },
      { time: "7:30 PM", home: "Cincinnati Bearcats", away: "Ball State Cardinals" },
      { time: "8:30 PM", home: "Texas Longhorns", away: "Missouri Tigers" },
      { time: "9:30 PM", home: "Hawaii Rainbow Warriors", away: "Michigan Wolverines" },
      { time: "10:00 PM", home: "Florida Gators", away: "Liberty Flames" },
    ],
  },
  {
    id: "week-5",
    title: "Week 5",
    auto: "7/30",
    games: [
      { time: "7:00 PM", home: "Hawaii Rainbow Warriors", away: "Liberty Flames" },
      { time: "7:30 PM", home: "Florida Gators", away: "Oregon State Beavers" },
      { time: "8:30 PM", home: "Missouri Tigers", away: "Ball State Cardinals" },
      { time: "9:30 PM", home: "Texas Longhorns", away: "Michigan Wolverines" },
      { time: "10:00 PM", home: "Cincinnati Bearcats", away: "Oregon Ducks" },
    ],
  },
  {
    id: "week-6",
    title: "Week 6",
    auto: "8/3",
    games: [
      { time: "7:00 PM", home: "Cincinnati Bearcats", away: "Florida Gators" },
      { time: "7:30 PM", home: "Missouri Tigers", away: "Oregon Ducks" },
      { time: "8:30 PM", home: "Texas Longhorns", away: "Ball State Cardinals" },
      { time: "9:30 PM", home: "Hawaii Rainbow Warriors", away: "Oregon State Beavers" },
      { time: "10:00 PM", home: "Michigan Wolverines", away: "Liberty Flames" },
    ],
  },
  {
    id: "week-7",
    title: "Week 7",
    auto: "8/11",
    games: [
      { time: "7:00 PM", home: "Ball State Cardinals", away: "Oregon Ducks" },
      { time: "7:30 PM", home: "Hawaii Rainbow Warriors", away: "Cincinnati Bearcats" },
      { time: "8:30 PM", home: "Missouri Tigers", away: "Florida Gators" },
      { time: "9:30 PM", home: "Michigan Wolverines", away: "Oregon State Beavers" },
      { time: "10:00 PM", home: "Texas Longhorns", away: "Liberty Flames" },
    ],
  },
  {
    id: "week-8",
    title: "Week 8",
    auto: "8/15",
    games: [
      { time: "7:00 PM", home: "Michigan Wolverines", away: "Cincinnati Bearcats" },
      { time: "7:30 PM", home: "Texas Longhorns", away: "Oregon Ducks" },
      { time: "8:30 PM", home: "Missouri Tigers", away: "Hawaii Rainbow Warriors" },
      { time: "9:30 PM", home: "Ball State Cardinals", away: "Florida Gators" },
      { time: "10:00 PM", home: "Liberty Flames", away: "Oregon State Beavers" },
    ],
  },
  {
    id: "week-9",
    title: "Week 9",
    auto: "8/19",
    games: [
      { time: "7:00 PM", home: "Liberty Flames", away: "Cincinnati Bearcats" },
      { time: "7:30 PM", home: "Michigan Wolverines", away: "Missouri Tigers" },
      { time: "8:30 PM", home: "Oregon Ducks", away: "Florida Gators" },
      { time: "9:30 PM", home: "Texas Longhorns", away: "Oregon State Beavers" },
      { time: "10:00 PM", home: "Ball State Cardinals", away: "Hawaii Rainbow Warriors" },
    ],
  },
  {
    id: "week-10",
    title: "Week 10",
    auto: "8/23",
    games: [
      { time: "7:00 PM", home: "Oregon State Beavers", away: "Cincinnati Bearcats" },
      { time: "7:30 PM", home: "Oregon Ducks", away: "Hawaii Rainbow Warriors" },
      { time: "8:30 PM", home: "Liberty Flames", away: "Missouri Tigers" },
      { time: "9:30 PM", home: "Ball State Cardinals", away: "Michigan Wolverines" },
      { time: "10:00 PM", home: "Texas Longhorns", away: "Florida Gators" },
    ],
  },
  {
    id: "week-11",
    title: "Week 11",
    auto: "8/27",
    games: [
      { time: "7:00 PM", home: "Florida Gators", away: "Hawaii Rainbow Warriors" },
      { time: "7:30 PM", home: "Liberty Flames", away: "Ball State Cardinals" },
      { time: "8:30 PM", home: "Oregon State Beavers", away: "Missouri Tigers" },
      { time: "9:30 PM", home: "Texas Longhorns", away: "Cincinnati Bearcats" },
      { time: "10:00 PM", home: "Oregon Ducks", away: "Michigan Wolverines" },
    ],
  },
  {
    id: "week-12",
    title: "Week 12",
    auto: "8/31",
    games: [
      { time: "7:00 PM", home: "Oregon State Beavers", away: "Ball State Cardinals" },
      { time: "7:30 PM", home: "Texas Longhorns", away: "Hawaii Rainbow Warriors" },
      { time: "8:30 PM", home: "Florida Gators", away: "Michigan Wolverines" },
      { time: "9:30 PM", home: "Oregon Ducks", away: "Liberty Flames" },
      { time: "10:00 PM", home: "Cincinnati Bearcats", away: "Missouri Tigers" },
    ],
  },
  {
    id: "playoffs-r1",
    title: "Playoffs Round 1",
    auto: "9/5",
    games: [
      { time: "7:30 PM", home: "1", away: "8", seed: true },
      { time: "8:00 PM", home: "2", away: "7", seed: true },
      { time: "8:30 PM", home: "3", away: "6", seed: true },
      { time: "9:00 PM", home: "4", away: "5", seed: true },
    ],
  },
  {
    id: "playoffs-r2",
    title: "Playoffs Round 2",
    auto: "9/10",
    games: [
      { time: "8:00 PM", home: "Highest seed", away: "Lowest seed", seed: true },
      { time: "9:00 PM", home: "N/A", away: "N/A", seed: true },
    ],
  },
  {
    id: "championship",
    title: "Championship",
    auto: "9/15",
    games: [{ time: "9:30 PM", home: "N/A", away: "N/A", seed: true }],
  },
];
